version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bookvito_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookvito
    ports:
      - "5432:5432"
    volumes:
      # Option 1: Named volume (recommended, already active)
      - postgres_data:/var/lib/postgresql/data
      
      # Option 2: Local directory (uncomment to use local storage)
      # - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Go API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookvito_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: bookvito
      DB_SSLMODE: disable
      SERVER_PORT: 8080
      JWT_SECRET: your-secret-key-here
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
